### ISSUE TITLE
请问yolov8_x_mask-refine_syncbn_fast_8xb16-500e_coco.pth在哪里找

### ISSUE THREAD

**Issue by Yuehongzhe** [Pointcept/OpenIns3D#18]
Loads checkpoint by local backend from path: /media/Disk/OpenIns3D-main/third_party/YOLO-World/third_party/mmyolo/checkpoints/yolov8_x_mask-refine_syncbn_fast_8xb16-500e_coco.pth
Traceback (most recent call last):
  File "/media/Disk/OpenIns3D-main/openins3d/main.py", line 270, in <module>
    openins3d = OpenIns3D(dataset_name.lower(), dataset_path, image_detector = args.detector, mode = args.task, use_2d = args.use_2d, vis = args.save_vis)
  File "/media/Disk/OpenIns3D-main/openins3d/main.py", line 37, in __init__
    self.lookup.call_YOLOWORLD()
  File "/media/Disk/OpenIns3D-main/openins3d/lookup.py", line 40, in call_YOLOWORLD
    self.YOLOWORLD = YOLOWORLD(self.snap_folder, self.results_folder, self.text_input)
  File "/media/Disk/OpenIns3D-main/openins3d/build_lookup_yoloworld.py", line 40, in __init__
    self.load_yolo()
  File "/media/Disk/OpenIns3D-main/openins3d/build_lookup_yoloworld.py", line 69, in load_yolo
    self.runner.load_or_resume()
  File "/home/wsco2/anaconda3/envs/openins3d/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1699, in load_or_resume
    self.load_checkpoint(self._load_from)
  File "/home/wsco2/anaconda3/envs/openins3d/lib/python3.9/site-packages/mmengine/runner/runner.py", line 2127, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location=map_location)
  File "/home/wsco2/anaconda3/envs/openins3d/lib/python3.9/site-packages/mmengine/runner/checkpoint.py", line 548, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/home/wsco2/anaconda3/envs/openins3d/lib/python3.9/site-packages/mmengine/runner/checkpoint.py", line 330, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/home/wsco2/anaconda3/envs/openins3d/lib/python3.9/site-packages/mmengine/runner/checkpoint.py", line 346, in load_from_local
    raise FileNotFoundError(f'{filename} can not be found.')
FileNotFoundError: /media/Disk/OpenIns3D-main/third_party/YOLO-World/third_party/mmyolo/checkpoints/yolov8_x_mask-refine_syncbn_fast_8xb16-500e_coco.pth can not be found.

**Comment by ZheningHuang** [comment]
`sh scripts/prepare_yoloworld.sh `

**Comment by ZheningHuang** [comment]
这边测试过应该没有问题，有问题请再联系，谢谢。
